### ISSUE TITLE
Redirect doesn't work with Link component

### ISSUE THREAD

**Issue by paulwehner** [trandainhan/next.js-example-authentication-with-jwt#2]
If I add:

```
<Link href="/">Home</Link>
```

Onto the login.js, and then click the Link that is generated, I can access the index.js without being logged in. How would you suggest fixing this?

Thanks for the simple example so far.

**Comment by paulwehner** [comment]
I guess one solution would be to manually change the Link components depending on whether someone is logged in or coming from the Login page. Would be nice is the Link component was aware of the security though and re-routed the same way as done in the server.js.

**Comment by trandainhan** [comment]
This also happen when you use `Router.push({pahtname: /})`. Under the hood, Link actually use next/router to push new path into browser history. All of these things are handled on browser, and i think there are nothing to do here for our middleware on server side. I agree with your suggestion, you can create your own Link component and check cookie whenever we change the url.

**Comment by DanWebb** [comment]
What about a simple authenticate method that calls an api route if `req` doesn't exist on getInitialProps for pages that require authentication.
```
const authenticate = req => {
	if (req) {
		return Promise.resolve({loggedIn: true});
	}

       return fetch('/api/authenticate', {
	        credentials: 'same-origin',
       })
       .then(res => {
                if(res.status === 401) {
                     return logout()
                }

                return Promise.resolve({loggedIn: true});
       })
};
```

```
static async getInitialProps({req}) {
	const loggedIn = await authenticate(req);
	return loggedIn;
}
```

Setting credentials on the fetch should send the access token cookie with it so the token can be verified the same way as it is currently on the server. Just send a 401 instead of redirecting.
